/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  InvoicesApi,
  SearchInvoicesApi,
  TemplatesApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { PayPalInvoicingCustom } from "./client-custom";

export class PayPalInvoicing extends PayPalInvoicingCustom {
  readonly invoices: InvoicesApi;
  readonly searchInvoices: SearchInvoicesApi;
  readonly templates: TemplatesApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.invoices = new InvoicesApi(configuration);
    this.searchInvoices = new SearchInvoicesApi(configuration);
    this.templates = new TemplatesApi(configuration);
  }

}
