/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The non-portable additional address details that are sometimes needed for compliance, risk, or other scenarios where fine-grain address information might be needed. Not portable with common third party and open source. Redundant with core fields.<br/>For example, `address_portable.address_line_1` is usually a combination of `address_details.street_number`, `street_name`, and `street_type`.
 * @export
 * @interface AddressDetailsProperty
 */
export interface AddressDetailsProperty {
    /**
     * The street number.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'street_number'?: string;
    /**
     * The street name. Just `Drury` in `Drury Lane`.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'street_name'?: string;
    /**
     * The street type. For example, avenue, boulevard, road, or expressway.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'street_type'?: string;
    /**
     * The delivery service. Post office box, bag number, or post office name.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'delivery_service'?: string;
    /**
     * A named locations that represents the premise. Usually a building name or number or collection of buildings with a common name or number. For example, <code>Craven House</code>.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'building_name'?: string;
    /**
     * The first-order entity below a named building or location that represents the sub-premise. Usually a single building within a collection of buildings with a common name. Can be a flat, story, floor, room, or apartment.
     * @type {string}
     * @memberof AddressDetailsProperty
     */
    'sub_building'?: string;
}

