/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AggregatedDiscount } from './aggregated-discount';
import { CustomAmount } from './custom-amount';
import { Money } from './money';
import { ShippingCost } from './shipping-cost';

/**
 * The breakdown of the amount. Includes total item amount, total tax amount, custom amount, and shipping and discounts, if any.
 * @export
 * @interface AmountWithBreakdown
 */
export interface AmountWithBreakdown {
    /**
     * 
     * @type {Money}
     * @memberof AmountWithBreakdown
     */
    'item_total'?: Money;
    /**
     * 
     * @type {AggregatedDiscount}
     * @memberof AmountWithBreakdown
     */
    'discount'?: AggregatedDiscount;
    /**
     * 
     * @type {Money}
     * @memberof AmountWithBreakdown
     */
    'tax_total'?: Money;
    /**
     * 
     * @type {ShippingCost}
     * @memberof AmountWithBreakdown
     */
    'shipping'?: ShippingCost;
    /**
     * 
     * @type {CustomAmount}
     * @memberof AmountWithBreakdown
     */
    'custom'?: CustomAmount;
}

