/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PhoneDetail } from './phone-detail';

/**
 * 
 * @export
 * @interface BillingInfoAllOf
 */
export interface BillingInfoAllOf {
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof BillingInfoAllOf
     */
    'email_address'?: string;
    /**
     * The invoice recipient\'s phone numbers. Extension number is not supported.
     * @type {Array<PhoneDetail>}
     * @memberof BillingInfoAllOf
     */
    'phones'?: Array<PhoneDetail>;
    /**
     * Any additional information about the recipient.
     * @type {string}
     * @memberof BillingInfoAllOf
     */
    'additional_info'?: string;
    /**
     * The [language tag](https://tools.ietf.org/html/bcp47#section-2) for the language in which to localize the error-related strings, such as messages, issues, and suggested actions. The tag is made up of the [ISO 639-2 language code](https://www.loc.gov/standards/iso639-2/php/code_list.php), the optional [ISO-15924 script tag](https://www.unicode.org/iso15924/codelists.html), and the [ISO-3166 alpha-2 country code](https://raw.githubusercontent.com).
     * @type {string}
     * @memberof BillingInfoAllOf
     */
    'language'?: string;
}

