/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FileReference } from './file-reference';

/**
 * The details of the invoice like notes, terms and conditions, memo, attachments.
 * @export
 * @interface Detail
 */
export interface Detail {
    /**
     * The reference data. Includes a post office (PO) number.
     * @type {string}
     * @memberof Detail
     */
    'reference'?: string;
    /**
     * The [three-character ISO-4217 currency code](https://raw.githubusercontent.com) that identifies the currency.
     * @type {string}
     * @memberof Detail
     */
    'currency_code': string;
    /**
     * A note to the invoice recipient. Also appears on the invoice notification email.
     * @type {string}
     * @memberof Detail
     */
    'note'?: string;
    /**
     * The general terms of the invoice. Can include return or cancellation policy and other terms and conditions.
     * @type {string}
     * @memberof Detail
     */
    'terms_and_conditions'?: string;
    /**
     * A private bookkeeping memo for the user.
     * @type {string}
     * @memberof Detail
     */
    'memo'?: string;
    /**
     * An array of PayPal IDs for the files that are attached to an invoice.
     * @type {Array<FileReference>}
     * @memberof Detail
     */
    'attachments'?: Array<FileReference>;
}

