/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error400 } from './error400';
import { Error401 } from './error401';
import { Error403 } from './error403';
import { Error404 } from './error404';
import { Error409 } from './error409';
import { Error415 } from './error415';
import { Error422 } from './error422';
import { Error500 } from './error500';
import { Error503 } from './error503';
import { ErrorDetails } from './error-details';
import { ErrorLinkDescription } from './error-link-description';

/**
 * @type ErrorDefault
 * The default error response.
 * @export
 */
export type ErrorDefault = Error400 | Error401 | Error403 | Error404 | Error409 | Error415 | Error422 | Error500 | Error503;


