/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information.
 * @export
 * @interface ErrorLinkDescription
 */
export interface ErrorLinkDescription {
    /**
     * The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call.
     * @type {string}
     * @memberof ErrorLinkDescription
     */
    'href': string;
    /**
     * The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml).
     * @type {string}
     * @memberof ErrorLinkDescription
     */
    'rel': string;
    /**
     * The HTTP method required to make the related call.
     * @type {string}
     * @memberof ErrorLinkDescription
     */
    'method'?: ErrorLinkDescriptionMethodEnum;
}

type ErrorLinkDescriptionMethodEnum = 'CONNECT' | 'DELETE' | 'GET' | 'HEAD' | 'OPTIONS' | 'PATCH' | 'POST' | 'PUT'


