/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDetails } from './error-details';
import { ErrorLinkDescription } from './error-link-description';

/**
 * The server has not found anything matching the request URI. This either means that the URI is incorrect or the resource is not available.
 * @export
 * @interface Error404
 */
export interface Error404 {
    /**
     * 
     * @type {string}
     * @memberof Error404
     */
    'name'?: Error404NameEnum;
    /**
     * 
     * @type {string}
     * @memberof Error404
     */
    'message'?: Error404MessageEnum;
    /**
     * 
     * @type {Array<ErrorDetails>}
     * @memberof Error404
     */
    'details'?: Array<ErrorDetails>;
    /**
     * The PayPal internal ID. Used for correlation purposes.
     * @type {string}
     * @memberof Error404
     */
    'debug_id'?: string;
    /**
     * An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
     * @type {Array<ErrorLinkDescription>}
     * @memberof Error404
     */
    'links'?: Array<ErrorLinkDescription>;
}

type Error404NameEnum = 'RESOURCE_NOT_FOUND'
type Error404MessageEnum = 'The specified resource does not exist.'


