/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The file reference. Can be a file in PayPal MediaServ, PayPal DMS, or other custom store.
 * @export
 * @interface FileReference
 */
export interface FileReference {
    /**
     * The ID of the referenced file.
     * @type {string}
     * @memberof FileReference
     */
    'id'?: string;
    /**
     * The reference URL for the file.
     * @type {string}
     * @memberof FileReference
     */
    'reference_url'?: string;
    /**
     * The [Internet Assigned Numbers Authority (IANA) media type of the file](https://www.iana.org/assignments/media-types/media-types.xhtml).
     * @type {string}
     * @memberof FileReference
     */
    'content_type'?: string;
    /**
     * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
     * @type {string}
     * @memberof FileReference
     */
    'create_time'?: string;
    /**
     * The size of the file, in bytes.
     * @type {string}
     * @memberof FileReference
     */
    'size'?: string;
}

