/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PhoneDetail } from './phone-detail';

/**
 * 
 * @export
 * @interface InvoicerInfoAllOf
 */
export interface InvoicerInfoAllOf {
    /**
     * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
     * @type {string}
     * @memberof InvoicerInfoAllOf
     */
    'email_address'?: string;
    /**
     * An array of invoicer\'s phone numbers. The invoicer can choose to hide the phone number on the invoice.
     * @type {Array<PhoneDetail>}
     * @memberof InvoicerInfoAllOf
     */
    'phones'?: Array<PhoneDetail>;
    /**
     * The invoicer\'s website.
     * @type {string}
     * @memberof InvoicerInfoAllOf
     */
    'website'?: string;
    /**
     * The invoicer\'s tax ID.
     * @type {string}
     * @memberof InvoicerInfoAllOf
     */
    'tax_id'?: string;
    /**
     * Any additional information. Includes business hours.
     * @type {string}
     * @memberof InvoicerInfoAllOf
     */
    'additional_notes'?: string;
    /**
     * The full URL to an external logo image. The logo image must not be larger than 250 pixels wide by 90 pixels high.
     * @type {string}
     * @memberof InvoicerInfoAllOf
     */
    'logo_url'?: string;
}

