/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InvoicePaymentTerm } from './invoice-payment-term';
import { Metadata } from './metadata';

/**
 * 
 * @export
 * @interface InvoiceDetailAllOf
 */
export interface InvoiceDetailAllOf {
    /**
     * The invoice number. Default is the number that is auto-incremented number from the last number.
     * @type {string}
     * @memberof InvoiceDetailAllOf
     */
    'invoice_number'?: string;
    /**
     * The stand-alone date, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). To represent special legal values, such as a date of birth, you should use dates with no associated time or time-zone data. Whenever possible, use the standard `date_time` type. This regular expression does not validate all dates. For example, February 31 is valid and nothing is known about leap years.
     * @type {string}
     * @memberof InvoiceDetailAllOf
     */
    'invoice_date'?: string;
    /**
     * 
     * @type {InvoicePaymentTerm}
     * @memberof InvoiceDetailAllOf
     */
    'payment_term'?: InvoicePaymentTerm;
    /**
     * 
     * @type {Metadata}
     * @memberof InvoiceDetailAllOf
     */
    'metadata'?: Metadata;
}

