/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INVALIDDECIMALVALUE } from './invaliddecimalvalue';
import { INVALIDINTEGERVALUE } from './invalidintegervalue';
import { INVALIDPARAMETERSYNTAX5 } from './invalidparametersyntax5';
import { INVALIDPARAMETERSYNTAX6 } from './invalidparametersyntax6';
import { INVALIDPAYMENTMETHOD } from './invalidpaymentmethod';
import { INVALIDSTRINGLENGTH5 } from './invalidstringlength5';
import { INVALIDSTRINGMAXLENGTH27 } from './invalidstringmaxlength27';
import { MISSINGREQUIREDPARAMETER } from './missingrequiredparameter';
import { MISSINGREQUIREDPARAMETER1 } from './missingrequiredparameter1';
import { NOTSUPPORTED } from './notsupported';
import { VALUECANNOTBEZERO } from './valuecannotbezero';

/**
 * @type InvoicesPayments400DetailsInner
 * @export
 */
export type InvoicesPayments400DetailsInner = MISSINGREQUIREDPARAMETER | INVALIDPAYMENTMETHOD | NOTSUPPORTED | INVALIDSTRINGLENGTH5 | MISSINGREQUIREDPARAMETER1 | INVALIDSTRINGMAXLENGTH27 | INVALIDPARAMETERSYNTAX5 | VALUECANNOTBEZERO | INVALIDDECIMALVALUE | INVALIDINTEGERVALUE | INVALIDPARAMETERSYNTAX6;


