/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Invoice } from './invoice';
import { LinkDescription } from './link-description';

/**
 * An array of merchant invoices. Includes the total invoices count and [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links) for navigation.
 * @export
 * @interface Invoices
 */
export interface Invoices {
    /**
     * The total number of pages that are available for the search criteria. <blockquote><strong>Note:</strong> Clients MUST NOT assume that the value of total_pages is constant. The value MAY change from one request to the next</blockquote>
     * @type {number}
     * @memberof Invoices
     */
    'total_pages'?: number;
    /**
     * The total number of invoices that match the search criteria.<blockquote><strong>Note:</strong> Clients MUST NOT assume that the value of <code>total_items</code> is constant. The value MAY change from one request to the next.</blockquote>
     * @type {number}
     * @memberof Invoices
     */
    'total_items'?: number;
    /**
     * The list of invoices that match the search criteria.
     * @type {Array<Invoice>}
     * @memberof Invoices
     */
    'items'?: Array<Invoice>;
    /**
     * An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
     * @type {Array<LinkDescription>}
     * @memberof Invoices
     */
    'links'?: Array<LinkDescription>;
}

