/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INVALIDDECIMALVALUE1 } from './invaliddecimalvalue1';
import { INVALIDINTEGERVALUE1 } from './invalidintegervalue1';
import { INVALIDPARAMETERSYNTAX5 } from './invalidparametersyntax5';
import { INVALIDPARAMETERSYNTAX7 } from './invalidparametersyntax7';
import { INVALIDREFUNDMETHOD } from './invalidrefundmethod';
import { INVALIDSTRINGLENGTH5 } from './invalidstringlength5';
import { INVALIDSTRINGMAXLENGTH27 } from './invalidstringmaxlength27';
import { MISSINGREQUIREDPARAMETER } from './missingrequiredparameter';
import { MISSINGREQUIREDPARAMETER1 } from './missingrequiredparameter1';
import { NOTSUPPORTED1 } from './notsupported1';
import { VALUECANNOTBEZERO1 } from './valuecannotbezero1';

/**
 * @type InvoicesRefunds400DetailsInner
 * @export
 */
export type InvoicesRefunds400DetailsInner = MISSINGREQUIREDPARAMETER | INVALIDREFUNDMETHOD | INVALIDPARAMETERSYNTAX7 | INVALIDSTRINGLENGTH5 | NOTSUPPORTED1 | MISSINGREQUIREDPARAMETER1 | INVALIDPARAMETERSYNTAX5 | INVALIDSTRINGMAXLENGTH27 | VALUECANNOTBEZERO1 | INVALIDINTEGERVALUE1 | INVALIDDECIMALVALUE1;


