/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INVALIDPARAMETERSYNTAX } from './invalidparametersyntax';
import { INVALIDPARAMETERSYNTAX1 } from './invalidparametersyntax1';
import { INVALIDPARAMETERSYNTAX2 } from './invalidparametersyntax2';
import { INVALIDPARAMETERSYNTAX3 } from './invalidparametersyntax3';
import { INVALIDPARAMETERSYNTAX4 } from './invalidparametersyntax4';
import { INVALIDSTRINGLENGTH } from './invalidstringlength';
import { INVALIDSTRINGLENGTH1 } from './invalidstringlength1';
import { INVALIDSTRINGLENGTH2 } from './invalidstringlength2';
import { INVALIDSTRINGLENGTH3 } from './invalidstringlength3';
import { INVALIDSTRINGLENGTH4 } from './invalidstringlength4';
import { INVALIDSTRINGLENGTH5 } from './invalidstringlength5';
import { INVALIDSTRINGLENGTH6 } from './invalidstringlength6';
import { INVALIDSTRINGLENGTH7 } from './invalidstringlength7';
import { INVALIDSTRINGLENGTH8 } from './invalidstringlength8';
import { INVALIDSTRINGLENGTH9 } from './invalidstringlength9';
import { INVALIDSTRINGMAXLENGTH } from './invalidstringmaxlength';
import { INVALIDSTRINGMAXLENGTH1 } from './invalidstringmaxlength1';
import { INVALIDSTRINGMAXLENGTH10 } from './invalidstringmaxlength10';
import { INVALIDSTRINGMAXLENGTH11 } from './invalidstringmaxlength11';
import { INVALIDSTRINGMAXLENGTH12 } from './invalidstringmaxlength12';
import { INVALIDSTRINGMAXLENGTH13 } from './invalidstringmaxlength13';
import { INVALIDSTRINGMAXLENGTH14 } from './invalidstringmaxlength14';
import { INVALIDSTRINGMAXLENGTH15 } from './invalidstringmaxlength15';
import { INVALIDSTRINGMAXLENGTH16 } from './invalidstringmaxlength16';
import { INVALIDSTRINGMAXLENGTH17 } from './invalidstringmaxlength17';
import { INVALIDSTRINGMAXLENGTH18 } from './invalidstringmaxlength18';
import { INVALIDSTRINGMAXLENGTH19 } from './invalidstringmaxlength19';
import { INVALIDSTRINGMAXLENGTH2 } from './invalidstringmaxlength2';
import { INVALIDSTRINGMAXLENGTH20 } from './invalidstringmaxlength20';
import { INVALIDSTRINGMAXLENGTH21 } from './invalidstringmaxlength21';
import { INVALIDSTRINGMAXLENGTH22 } from './invalidstringmaxlength22';
import { INVALIDSTRINGMAXLENGTH23 } from './invalidstringmaxlength23';
import { INVALIDSTRINGMAXLENGTH24 } from './invalidstringmaxlength24';
import { INVALIDSTRINGMAXLENGTH3 } from './invalidstringmaxlength3';
import { INVALIDSTRINGMAXLENGTH4 } from './invalidstringmaxlength4';
import { INVALIDSTRINGMAXLENGTH5 } from './invalidstringmaxlength5';
import { INVALIDSTRINGMAXLENGTH6 } from './invalidstringmaxlength6';
import { INVALIDSTRINGMAXLENGTH7 } from './invalidstringmaxlength7';
import { INVALIDSTRINGMAXLENGTH8 } from './invalidstringmaxlength8';
import { INVALIDSTRINGMAXLENGTH9 } from './invalidstringmaxlength9';

/**
 * @type InvoicesCreate400DetailsInner
 * @export
 */
export type InvoicesCreate400DetailsInner = INVALIDSTRINGMAXLENGTH | INVALIDSTRINGLENGTH | INVALIDSTRINGMAXLENGTH1 | INVALIDPARAMETERSYNTAX | INVALIDSTRINGMAXLENGTH2 | INVALIDSTRINGMAXLENGTH3 | INVALIDSTRINGLENGTH1 | INVALIDSTRINGMAXLENGTH4 | INVALIDSTRINGLENGTH2 | INVALIDSTRINGMAXLENGTH5 | INVALIDSTRINGLENGTH3 | INVALIDSTRINGLENGTH4 | INVALIDSTRINGLENGTH5 | INVALIDSTRINGMAXLENGTH6 | INVALIDSTRINGMAXLENGTH7 | INVALIDSTRINGLENGTH6 | INVALIDSTRINGMAXLENGTH8 | INVALIDSTRINGMAXLENGTH9 | INVALIDSTRINGMAXLENGTH10 | INVALIDSTRINGMAXLENGTH11 | INVALIDPARAMETERSYNTAX1 | INVALIDSTRINGMAXLENGTH12 | INVALIDSTRINGMAXLENGTH13 | INVALIDSTRINGLENGTH7 | INVALIDSTRINGMAXLENGTH14 | INVALIDSTRINGMAXLENGTH15 | INVALIDSTRINGMAXLENGTH16 | INVALIDSTRINGMAXLENGTH17 | INVALIDPARAMETERSYNTAX2 | INVALIDSTRINGMAXLENGTH18 | INVALIDSTRINGLENGTH8 | INVALIDSTRINGMAXLENGTH19 | INVALIDSTRINGMAXLENGTH20 | INVALIDSTRINGMAXLENGTH21 | INVALIDPARAMETERSYNTAX3 | INVALIDSTRINGLENGTH9 | INVALIDSTRINGMAXLENGTH22 | INVALIDPARAMETERSYNTAX4 | INVALIDSTRINGMAXLENGTH23 | INVALIDSTRINGMAXLENGTH24;


