/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InvoiceCreationFlow } from './invoice-creation-flow';

/**
 * 
 * @export
 * @interface MetadataAllOf
 */
export interface MetadataAllOf {
    /**
     * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
     * @type {string}
     * @memberof MetadataAllOf
     */
    'cancel_time'?: string;
    /**
     * The actor who canceled the resource.
     * @type {string}
     * @memberof MetadataAllOf
     */
    'cancelled_by'?: string;
    /**
     * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
     * @type {string}
     * @memberof MetadataAllOf
     */
    'first_sent_time'?: string;
    /**
     * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
     * @type {string}
     * @memberof MetadataAllOf
     */
    'last_sent_time'?: string;
    /**
     * The email address of the account that last sent the resource.
     * @type {string}
     * @memberof MetadataAllOf
     */
    'last_sent_by'?: string;
    /**
     * The frequency at which the invoice is sent:<ul><li>Multiple recipient. Sent to multiple recipients.</li><li>Batch. Sent in a batch.</li><li>Regular single. Sent one time to a single recipient.</li></ul>
     * @type {InvoiceCreationFlow}
     * @memberof MetadataAllOf
     */
    'created_by_flow'?: InvoiceCreationFlow;
    /**
     * The URL for the invoice payer view hosted on paypal.com.
     * @type {string}
     * @memberof MetadataAllOf
     */
    'recipient_view_url'?: string;
    /**
     * The URL for the invoice merchant view hosted on paypal.com.
     * @type {string}
     * @memberof MetadataAllOf
     */
    'invoicer_view_url'?: string;
}

