/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The name of the party.
 * @export
 * @interface Name
 */
export interface Name {
    /**
     * The prefix, or title, to the party\'s name.
     * @type {string}
     * @memberof Name
     */
    'prefix'?: string;
    /**
     * When the party is a person, the party\'s given, or first, name.
     * @type {string}
     * @memberof Name
     */
    'given_name'?: string;
    /**
     * When the party is a person, the party\'s surname or family name. Also known as the last name. Required when the party is a person. Use also to store multiple surnames including the matronymic, or mother\'s, surname.
     * @type {string}
     * @memberof Name
     */
    'surname'?: string;
    /**
     * When the party is a person, the party\'s middle name. Use also to store multiple middle names including the patronymic, or father\'s, middle name.
     * @type {string}
     * @memberof Name
     */
    'middle_name'?: string;
    /**
     * The suffix for the party\'s name.
     * @type {string}
     * @memberof Name
     */
    'suffix'?: string;
    /**
     * DEPRECATED. The party\'s alternate name. Can be a business name, nickname, or any other name that cannot be split into first, last name. Required when the party is a business.
     * @type {string}
     * @memberof Name
     */
    'alternate_full_name'?: string;
    /**
     * When the party is a person, the party\'s full name.
     * @type {string}
     * @memberof Name
     */
    'full_name'?: string;
}

