/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The email or SMS notification to send to the invoicer or payer on sending an invoice.
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * The subject of the email that is sent as a notification to the recipient.
     * @type {string}
     * @memberof Notification
     */
    'subject'?: string;
    /**
     * A note to the payer.
     * @type {string}
     * @memberof Notification
     */
    'note'?: string;
    /**
     * Indicates whether to send a copy of the email to the merchant.
     * @type {boolean}
     * @memberof Notification
     */
    'send_to_invoicer'?: boolean;
    /**
     * Indicates whether to send a copy of the email to the recipient.
     * @type {boolean}
     * @memberof Notification
     */
    'send_to_recipient'?: boolean;
    /**
     * An array of one or more CC: emails to which notifications are sent. If you omit this parameter, a notification is sent to all CC: email addresses that are part of the invoice.<blockquote><strong>Note:</strong> Valid values are email addresses in the `additional_recipients` value associated with the invoice.</blockquote>
     * @type {Array<string>}
     * @memberof Notification
     */
    'additional_recipients'?: Array<string>;
}

