/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContactNameAddress } from './contact-name-address';
import { Money } from './money';
import { PaymentMethod } from './payment-method';
import { PaymentType } from './payment-type';

/**
 * The payment details of the invoice. Includes payment type, method, date, discount, and transaction type.
 * @export
 * @interface PaymentDetail
 */
export interface PaymentDetail {
    /**
     * The payment type. Can be PayPal or an external payment. Includes cash or a check.
     * @type {PaymentType}
     * @memberof PaymentDetail
     */
    'type'?: PaymentType;
    /**
     * The ID for a PayPal payment transaction. Required for the `PAYPAL` payment type.
     * @type {string}
     * @memberof PaymentDetail
     */
    'payment_id'?: string;
    /**
     * The stand-alone date, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). To represent special legal values, such as a date of birth, you should use dates with no associated time or time-zone data. Whenever possible, use the standard `date_time` type. This regular expression does not validate all dates. For example, February 31 is valid and nothing is known about leap years.
     * @type {string}
     * @memberof PaymentDetail
     */
    'payment_date'?: string;
    /**
     * The payment mode or method through which the invoicer can accept the payments.
     * @type {PaymentMethod}
     * @memberof PaymentDetail
     */
    'method': PaymentMethod;
    /**
     * A note associated with an external cash or check payment.
     * @type {string}
     * @memberof PaymentDetail
     */
    'note'?: string;
    /**
     * 
     * @type {Money}
     * @memberof PaymentDetail
     */
    'amount'?: Money;
    /**
     * 
     * @type {ContactNameAddress}
     * @memberof PaymentDetail
     */
    'shipping_info'?: ContactNameAddress;
}

