/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PartialPayment } from './partial-payment';

/**
 * The template configuration details. Includes tax information, tip, and partial payment.
 * @export
 * @interface TemplateConfiguration
 */
export interface TemplateConfiguration {
    /**
     * Indicates whether the tax is calculated before or after a discount. If `false`, the tax is calculated before a discount. If `true`, the tax is calculated after a discount.
     * @type {boolean}
     * @memberof TemplateConfiguration
     */
    'tax_calculated_after_discount'?: boolean;
    /**
     * Indicates whether the unit price includes tax.
     * @type {boolean}
     * @memberof TemplateConfiguration
     */
    'tax_inclusive'?: boolean;
    /**
     * Indicates whether the invoice enables the customer to enter a tip amount during payment. If `true`, the invoice shows a tip amount field so that the customer can enter a tip amount. If `false`, the invoice does not show a tip amount field.<blockquote><strong>Note:</strong> This feature is not available for users in `Hong Kong`, `Taiwan`, `India`, or `Japan`.</blockquote>
     * @type {boolean}
     * @memberof TemplateConfiguration
     */
    'allow_tip'?: boolean;
    /**
     * 
     * @type {PartialPayment}
     * @memberof TemplateConfiguration
     */
    'partial_payment'?: PartialPayment;
}

