/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AmountSummaryDetail } from './amount-summary-detail';
import { InvoicerInfo } from './invoicer-info';
import { Item } from './item';
import { Money } from './money';
import { RecipientInfo } from './recipient-info';
import { TemplateConfiguration } from './template-configuration';
import { TemplateDetail } from './template-detail';

/**
 * The template details. Includes invoicer business information, invoice recipients, items, and configuration.
 * @export
 * @interface TemplateInfo
 */
export interface TemplateInfo {
    /**
     * 
     * @type {TemplateDetail}
     * @memberof TemplateInfo
     */
    'detail'?: TemplateDetail;
    /**
     * 
     * @type {InvoicerInfo}
     * @memberof TemplateInfo
     */
    'invoicer'?: InvoicerInfo;
    /**
     * The billing and shipping information. Includes name, email, address, phone, and language.
     * @type {Array<RecipientInfo>}
     * @memberof TemplateInfo
     */
    'primary_recipients'?: Array<RecipientInfo>;
    /**
     * An array of one or more CC: emails to which notifications are sent. If you omit this parameter, a notification is sent to all CC: email addresses that are part of the invoice.<blockquote><strong>Note:</strong> Valid values are email addresses in the `additional_recipients` value associated with the invoice.</blockquote>
     * @type {Array<string>}
     * @memberof TemplateInfo
     */
    'additional_recipients'?: Array<string>;
    /**
     * An array of invoice line-item information.
     * @type {Array<Item>}
     * @memberof TemplateInfo
     */
    'items'?: Array<Item>;
    /**
     * 
     * @type {TemplateConfiguration}
     * @memberof TemplateInfo
     */
    'configuration'?: TemplateConfiguration;
    /**
     * 
     * @type {AmountSummaryDetail}
     * @memberof TemplateInfo
     */
    'amount'?: AmountSummaryDetail;
    /**
     * 
     * @type {Money}
     * @memberof TemplateInfo
     */
    'due_amount'?: Money;
}

