/*
Invoices

Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

The version of the OpenAPI document: 2.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LinkDescription } from './link-description';
import { TemplateInfo } from './template-info';
import { TemplateSettings } from './template-settings';
import { UnitOfMeasure } from './unit-of-measure';

/**
 * The template with invoice details to load with all captured fields.
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * The ID of the template.
     * @type {string}
     * @memberof Template
     */
    'id'?: string;
    /**
     * The template name.<blockquote><strong>Note:</strong> The template name must be unique.</blockquote>
     * @type {string}
     * @memberof Template
     */
    'name'?: string;
    /**
     * Indicates whether this template is the default template. A invoicer can have one default template.
     * @type {boolean}
     * @memberof Template
     */
    'default_template'?: boolean;
    /**
     * 
     * @type {TemplateInfo}
     * @memberof Template
     */
    'template_info'?: TemplateInfo;
    /**
     * 
     * @type {TemplateSettings}
     * @memberof Template
     */
    'settings'?: TemplateSettings;
    /**
     * The unit of measure for the invoiced item.
     * @type {UnitOfMeasure}
     * @memberof Template
     */
    'unit_of_measure'?: UnitOfMeasure;
    /**
     * Indicates whether this template is a invoicer-created custom template. The system generates non-custom templates.
     * @type {boolean}
     * @memberof Template
     */
    'standard_template'?: boolean;
    /**
     * An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
     * @type {Array<LinkDescription>}
     * @memberof Template
     */
    'links'?: Array<LinkDescription>;
}

